# Generated by Django 6.0.2 on 2026-04-28 05:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_alter_project_completed_at'), ('api', '0003_alter_project_title'), ('api', '0004_alter_timerecord_hours_alter_timerecord_note_and_more'), ('api', '0005_alter_project_title_alter_timerecord_parent'), ('api', '0006_alter_timerecord_date'), ('api', '0007_alter_timerecord_date'), ('api', '0008_alter_timerecord_date'), ('api', '0009_alter_timerecord_date'), ('api', '0010_alter_timerecord_date'), ('api', '0011_project_grand_total_time_timerecord_total_time_and_more'), ('api', '0012_timerecord_milliseconds'), ('api', '0013_remove_timerecord_hours_and_more'), ('api', '0014_rename_time_timerecord_duration'), ('api', '0015_alter_timerecord_total_time'), ('api', '0016_alter_project_grand_total_time_and_more'), ('api', '0017_timerecord_dayslist'), ('api', '0018_remove_timerecord_dayslist_project_dayslist'), ('api', '0019_rename_dayslist_project_days_list'), ('api', '0020_remove_project_days_list'), ('api', '0021_alter_timerecord_note'), ('api', '0022_remove_timerecord_note')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='プロジェクト名')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='メモ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('grand_total_time', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_record', to='api.project')),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('duration', models.DurationField(default=datetime.timedelta(0), null=True)),
            ],
        ),
    ]
